networks:
  prometheus:
    name: prometheus
    driver: bridge

services:
  java-application:
    build:
      context: java-application
      dockerfile: Dockerfile
    container_name: java-application
    ports:
      - "8080:8080"
    networks:
      - prometheus

  prometheus:
    container_name: prometheus-svc
    image: prom/prometheus:v3.3.0
    ports: 
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command: --config.file=/etc/prometheus/prometheus.yaml
    networks:
      - prometheus

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./loki-data/loki.yaml:/etc/loki/loki.yaml
    ports:
      - "3100:3100"
      - "9096:9096"
    networks:
      - prometheus

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./loki-data/promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    networks:
      - prometheus

  grafana:
    image: grafana/grafana:11.6.1
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-data/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    networks:
      - prometheus

volumes:
  grafana-storage:
